In [1]:
import pandas as pd

In [2]:
df_graph_data = pd.read_csv("./data/gold/gephi_graph_data.csv")

In [5]:
df_graph_data.head()

,Id,Label,timeset,type,modularity_class,indegree,outdegree,degree,weighted indegree,weighted outdegree,weighted degree,Authority,Hub,componentnumber,strongcompnum,stat_inf_class,clustering,eigencentrality
0,064616126640-05,Air France-KLM,NaN,Companies & groups,11,0,23,23,0,45,45,0.000000,0.034947,0,23,0,0,0.000000
1,197502,Marie-Pierre VEDRENNE,NaN,Mep,11,60,0,60,90,0,90,0.060138,0.000000,0,22,0,0,0.317460
2,197581,NaN,NaN,NaN,0,99,0,99,229,0,229,0.094578,0.000000,0,21,0,0,0.523810
3,197529,Leila CHAIBI,NaN,Mep,3,47,0,47,63,0,63,0.034219,0.000000,0,20,0,0,0.248677
4,197589,Laurence FARRENG,NaN,Mep,11,47,0,47,133,0,133,0.039436,0.000000,0,19,0,0,0.248677

In [8]:
df_graph_data.groupby("modularity_class").agg(
    {"Id": "count", "degree": "mean", "Authority": "mean", "eigencentrality": "mean"}
).reset_index()

    modularity_class     Id     degree  Authority  eigencentrality
0                  0  13197   0.214064   0.000086         0.000572
1                  1    243   9.213992   0.003450         0.023341
2                  2    193  11.321244   0.004234         0.030869
3                  3    213  11.464789   0.004729         0.031373
4                  4    242   9.227273   0.003351         0.025668
5                  5    190  13.568421   0.007006         0.040156
6                  6    443  11.180587   0.004548         0.028784
7                  7     47  10.127660   0.003503         0.021839
8                  8    382  11.565445   0.004839         0.030098
9                  9    161   9.372671   0.003597         0.024187
10                10    528  11.539773   0.005312         0.029622
11                11    297  10.579125   0.004386         0.028593
12                12    246   9.739837   0.003202         0.025229
13                13    180  10.255556   0.003702         0.025514
14                14    179   9.458101   0.003992         0.026485

In [13]:
## A dataframe to get the top ten by authority by cluster

df_graph_data.groupby("modularity_class").apply(
    lambda x: x.sort_values("Hub", ascending=False).head(10)
).reset_index(drop=True).to_csv("./data/gold/top_ten_by_hub.csv", index=False)